version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
    ports:
      - '15432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "123456"
  #   ports:
  #     - "16543:80"

volumes:
  pgdata:
