version: '3.9'
services:
  revisiting_rails_api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  #   depends_on:
  #     - revisiting_db
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:password@revisiting_db:5432/revisiting_development

  # revisiting_db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: revisiting_development
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
