default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000
  host: revisiting_db
  username: revisiting_user
  password: password
  port: 5432

development:
  <<: *default
  database: revisiting_development

test:
  <<: *default
  database: revisiting_test
